services:
  postgres:
    container_name: postgres
    image: ghcr.io/0xpekenbower/42-transcendence/postgres:latest
    restart: always
    networks:
      - transcendence
    env_file:
      - ./infra/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: ghcr.io/0xpekenbower/42-transcendence/nginx:latest
    ports:
      - "4443:443"
    env_file:
      - ./infra/.env
    networks:
      - transcendence
    restart: always
    volumes:
      - ./infra/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./infra/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem:ro

networks:
  transcendence:
    external: true
    name: transcendence

volumes:
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      device: ./data/postgresdb
      o: bind 