services:
  postgres:
    container_name: postgres
    image: ghcr.io/0xpekenbower/42-transcendence/postgres:latest
    restart: always
    networks:
      - transcendence
    env_file:
      - ./infra/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: ghcr.io/0xpekenbower/42-transcendence/nginx:latest
    ports:
      - "8080:80"
    env_file:
      - ./infra/.env
    networks:
      - transcendence
    restart: always

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      device: ./data/postgresdb
      o: bind 