services:
  frontend:
    container_name: frontend
    image: ghcr.io/0xpekenbower/42-transcendence/frontend:latest
    restart: unless-stopped
    networks:
      - transcendence
    env_file:
      - app/.env
    expose:
      - "3000"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next

networks:
  transcendence:
    external: true
    name: transcendence 