services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    restart: unless-stopped
    networks:
      - transcendence
    env_file:
      - app/.env
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app

networks:
  transcendence:
    external: true
    name: transcendence 