services:
  backend:
    container_name: backend
    image: ghcr.io/0xpekenbower/42-transcendence/backend:latest
    restart: unless-stopped
    networks:
      - transcendence
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    
networks:
  transcendence:
    external: true
    name: transcendence
