FROM nginx:alpine


# Configuration will be copied
COPY ./conf/default.conf /etc/nginx/conf.d/default.conf

# SSL certificates will be mounted at runtime
# No need to generate them here

CMD ["nginx", "-g", "daemon off;"]