name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decrypt .env file
        run: |
          chmod +x ./gpg_tools.sh
          ./gpg_tools.sh decrypt

      - name: Deploy using Makefile
        run: |
          make all

      - name: Verify deployment
        run: |
          docker ps
          echo "Deployment completed successfully!" 